lab_name: Cal Poly Data Design Lab
institution: California Polytechnic State University, San Luis Obispo
short_institution: Cal Poly San Luis Obispo
tagline: Human-centered data science, visualization, and HCI.
email: awrigh20@calpoly.edu
location: San Luis Obispo, California
footer_note: >-
  This website and lab is informally maintained by the affiliated faculty and students and does not officially represent Cal Poly San Luis Obispo.
